# Generated by Django 4.2.20 on 2025-08-27 07:23

from django.db import migrations, models

from project.settings import MEDIA_URL


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocontentmodel",
            name="video_path",
            field=models.FileField(
                blank=True, null=True, upload_to= MEDIA_URL.lstrip("/") + "%Y/%m/%d/videos/"
            ),
        ),
    ]
