# Generated by Django 4.2.20 on 2025-08-27 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_videocontentmodel_video_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiocontentmodel",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="File is active or not",
                verbose_name="Is active",
            ),
        ),
        migrations.AddField(
            model_name="videocontentmodel",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="File is active or not",
                verbose_name="Is active",
            ),
        ),
        migrations.AlterField(
            model_name="videocontentmodel",
            name="subtitles_url",
            field=models.URLField(
                blank=True,
                help_text="Пример: 'https://hallo_word.ru/your-file.mp4'",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid URL!",
                        regex="(^https?:\\/\\/[a-z0-9-\\/_]+\\.(ru|com|net)\\/[a-z0-9-\\/_]+\\.[a-z]{2,4})",
                    )
                ],
                verbose_name="Subtitles URL",
            ),
        ),
        migrations.AlterField(
            model_name="videocontentmodel",
            name="video_path",
            field=models.FileField(
                blank=True,
                help_text="Пример: 'medio/2025/07/12/videos/your-file.mp4'",
                null=True,
                upload_to="medio/%Y/%m/%d/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="videocontentmodel",
            name="video_url",
            field=models.URLField(
                help_text="Пример: 'https://hallo_word.ru/your-file.mp4'",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid URL!",
                        regex="(^https?:\\/\\/[a-z0-9-\\/_]+\\.(ru|com|net)\\/[a-z0-9-\\/_]+\\.[a-z]{2,4})",
                    )
                ],
                verbose_name="Video URL",
            ),
        ),
    ]
