# Generated by Django 4.2.20 on 2025-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_audiocontentmodel_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiocontentmodel",
            name="is_active",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Inactive")],
                default=False,
                help_text="File is active or not",
                verbose_name="Is active",
            ),
        ),
        migrations.AlterField(
            model_name="videocontentmodel",
            name="is_active",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Inactive")],
                default=False,
                help_text="File is active or not",
                verbose_name="Is active",
            ),
        ),
    ]
