# Generated by Django 4.2.20 on 2025-08-27 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_audiocontentmodel_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagemodel",
            name="url",
            field=models.URLField(
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid URL!",
                        regex="(^https?:\\/\\/[a-z0-9-\\/_]+\\.(ru|com|net)\\/[a-z0-9-\\/_]+\\/$)",
                    )
                ],
                verbose_name="URL",
            ),
        ),
    ]
