# Generated by Django 4.2.20 on 2025-08-27 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_pagemodel_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videocontentmodel",
            name="video_url",
            field=models.URLField(
                help_text="Пример: 'https://hallo_word.ru/your-file.mp4'",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid URL!",
                        regex="(^https?:\\/\\/[a-z0-9-\\/_]+\\.(ru|com|net)\\/[a-z0-9-\\/_]+\\.[a-z4]{2,4})",
                    )
                ],
                verbose_name="Video URL",
            ),
        ),
    ]
