# Generated by Django 4.2.20 on 2025-08-27 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_videocontentmodel_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videocontentmodel",
            name="subtitles_url",
            field=models.URLField(
                blank=True,
                help_text="Указать URL на файл",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid URL!",
                        regex="(^https?:\\/\\/[a-z0-9-\\/_]+\\.(ru|com|net)\\/[a-z0-9-\\/_]+\\.[a-z4]{2,4})",
                    )
                ],
                verbose_name="Subtitles URL",
            ),
        ),
        migrations.AlterField(
            model_name="videocontentmodel",
            name="video_path",
            field=models.FileField(
                blank=True,
                help_text="Пример: 'media/2025/07/12/video/your-file.mp4'",
                null=True,
                upload_to="%Y/%m/%d/video/",
            ),
        ),
        migrations.AlterField(
            model_name="videocontentmodel",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Указать URL на файл",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid URL!",
                        regex="(^https?:\\/\\/[a-z0-9-\\/_]+\\.(ru|com|net)\\/[a-z0-9-\\/_]+\\.[a-z4]{2,4})",
                    )
                ],
                verbose_name="Video URL",
            ),
        ),
    ]
