# Generated by Django 4.2.20 on 2025-08-27 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_videocontentmodel_subtitles_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiocontentmodel",
            name="audio_path",
            field=models.FileField(
                blank=True,
                help_text="Пример: 'your-file.mp3'",
                upload_to="%Y/%m/%d/audio/",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid pathname!",
                        regex="(^[a-z][a-z0-9-\\/_]+\\/{0,1}[a-z0-9-\\/_]?\\.[a-z2-4]{2,4})",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="audiocontentmodel",
            name="audio_url",
            field=models.URLField(
                blank=True,
                help_text="Pathname to the audio file",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid URL!",
                        regex="(^https?:\\/\\/[a-z0-9-\\/_]+\\.(ru|com|net)\\/[a-z0-9-\\/_]+\\.[a-z2-4]{2,4})",
                    )
                ],
                verbose_name="Audio URL",
            ),
        ),
    ]
