# Generated by Django 4.2.20 on 2025-08-28 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_audiocontentmodel_audio_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiocontentmodel",
            name="audio_path",
            field=models.FileField(
                blank=True,
                help_text="Пример: 'your-file.mp3'",
                null=True,
                upload_to="%Y/%m/%d/audio/",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter valid pathname!",
                        regex="(^[a-z][a-z0-9-\\/_]+\\/{0,1}[a-z0-9-\\/_]?\\.[a-z2-4]{2,4})",
                    )
                ],
            ),
        ),
    ]
