# Generated by Django 4.2.20 on 2025-08-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_audiocontentmodel_audio_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiocontentmodel",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="videocontentmodel",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                editable=False,
                max_length=20,
            ),
        ),
    ]
